version: "3.8"
services:
  backend:
    build: './'
    container_name: 'easy-http-container'
    env_file: 
        - .\env\backend.env
        - .\env\routes.env
    ports: 
      - '3030:3030'
    volumes: 
        - ./app:/easy-http/app
    command: "npm start"